apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: leaderboard
    chart: leaderboard
    release: {{ .Release.Service }}
    component: leaderboard
spec:
  schedule: "{{ .Values.leaderboard.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: cloudsql-proxy
            image: gcr.io/cloudsql-docker/gce-proxy:1.11
            command:
            - /bin/sh
            args:
            - c
            - |
              tail -f /dev/null
              /cloud_sql_proxy \
              -instances={{ .Values.leaderboard.db.connection_name }}=tcp:5432 \
              -credential_file=/secrets/cloudsql/credentials.json
            securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
            volumeMounts:
            - name: blockscout-cloudsql-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          - name: update-sheet
            image: {{ .Values.leaderboard.image.repository }}:{{ .Values.leaderboard.image.tag }}
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh"]
            args:
            - "-c"
            - |
              ts-node src/board.ts
            env:
            - name: LEADERBOARD_DATABASE
              value: {{ .Values.leaderboard.database }}
            - name: LEADERBOARD_WEB3
              value: {{ .Values.leaderboard.web3 }}
            - name: LEADERBOARD_SPREET
              value: {{ .Values.leaderboard.spreet }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-leaderboard
                  key: DATABASE_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-leaderboard
                  key: DATABASE_PASSWORD
          restartPolicy: Never
          volumes:
          - name: blockscout-cloudsql-credentials
            secret:
              defaultMode: 420
              secretName: blockscout-cloudsql-credentials
