apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: leaderboard
    chart: leaderboard
    release: {{ .Release.Service }}
    component: leaderboard
spec:
  schedule: "{{ .Values.leaderboard.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: update-sheet
            image: {{ .Values.leaderboard.image.repository }}:{{ .Values.leaderboard.image.tag }}
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh"]
            args:
            - "-c"
            - |
              ts-node src/board.ts
            env:
            - name: LEADERBOARD_DATABASE
              value: {{ .Values.leaderboard.database }}
            - name: LEADERBOARD_TOKEN
              value: {{ .Values.leaderboard.token }}
            - name: LEADERBOARD_CREDENTIALS
              value: {{ .Values.leaderboard.credentials }}
            - name: LEADERBOARD_WEB3
              value: {{ .Values.leaderboard.web3 }}
            - name: LEADERBOARD_SPREET
              value: {{ .Values.leaderboard.spreet }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-leaderboard
                  key: DATABASE_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}-leaderboard
                  key: DATABASE_PASSWORD
          restartPolicy: Never
          volumes:
            - name: data
              emptyDir: {}
