apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Values.environment }}-eksportisto-{{ .Values.deploymentSuffix }}
  labels:
    app: eksportisto
    chart: eksportisto
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: eksportisto
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: eksportisto
      release: {{ .Release.Name }}
      component: eksportisto
  template:
    metadata:
      labels:
        app: eksportisto
        release: {{ .Release.Name }}
        component: eksportisto
    spec:
      containers:
      - name: eksportisto-{{ .Values.deploymentSuffix }}
        image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - bash
          - "-c"
          - |
            /rosetta/eksportisto --nodeUri $WEB3_PROVIDER
        resources:
          requests:
            memory: 856Mi
            cpu: 1200m
        volumeMounts:
        - name: data
          mountPath: /root/.eksportisto
        env:
        - name: WEB3_PROVIDER
          value: {{ .Values.web3Provider }}
      volumes:
      - name: data
        emptyDir: {}
