nodeSelector: {}

# Expects cron schedule syntax
leaderboard:
  schedule: "*/5 * * * *"
  image:
    repository: us.gcr.io/celo-testnet/celo-monorepo
    tag: leaderboard-a3ebba7e51f45b293a40b59017a7fe6dcca14801
  database: blockscout
  web3: https://baklava-forno.celo-testnet.org/
  sheet:
  db:
    username:
    password:
    connection_name:
